services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./src:/usr/src/app/src
